### ISSUE TITLE
Building Boom in Portland

### ISSUE THREAD

**Issue by kmorrice** [hackoregon/civic#166]
# Story Card Request

**Project: Housing 2018**
**Card Title: Building Boom in Portland**

## Description / Wireframe
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3445877/40461592-e634e6fe-5ec0-11e8-8a18-23247d76fb8e.gif)

We would like to show animations of building permits for single-family housing, multi-family housing, and ADUs. There are data going back to ~1994-1996 for each set, and we would like to feature heat maps that portray the density of permits up through 2017. We would also like to show either a bar chart or a time series indicating the number of building permits for these different categories over time. 

## Data Visualization / Design Concerns
> If you have specific design or data visualization concerns, mention them here

## Context
> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)

https://opendata.arcgis.com/datasets/4d04eba5e9934a26be530076cae65839_89.geojson

We need to filter on several fields, including NEW CLASS, and NEW TYPE.  

### How did we calculate this
>Description or link to GitHub description of data methodology

### See the source
>Link to API / data documentation on GitHub
>Link to original source data
http://gis-pdx.opendata.arcgis.com/datasets/residential-building-permits

**Comment by danmelton** [comment]
It looks we can use the ScreenGridMap Component in the library for this card

**Comment by kmorrice** [comment]
We also want to include either a bar chart or line chart that could be shown next to its respective animation. It shows the number of permits per year over time. 
![adus](https://user-images.githubusercontent.com/3445877/40857829-2db80552-6591-11e8-9727-9e0cf07e14e8.png)
![multi-family](https://user-images.githubusercontent.com/3445877/40857830-2dcf3a4c-6591-11e8-8f9b-f44435375d98.png)
![single-family](https://user-images.githubusercontent.com/3445877/40857831-2de5ae1c-6591-11e8-88ab-a35d9880fafb.png)

**Comment by adpeters** [comment]
API Details:

We are defining three categories of dwellings, each with a specific filter:

Single-Family: http://service.civicpdx.org/housing-affordability/api/permits/?new_type=Single+Family+Dwelling&new_class=New+Construction&is_adu=false

Multi-Family: http://service.civicpdx.org/housing-affordability/api/permits/?new_type=Apartments/Condos,Duplex,Rowhouse,Townhouse&new_class=New+Construction&is_adu=false

ADU: http://service.civicpdx.org/housing-affordability/api/permits/?is_adu=true&new_class=New+Construction,Alteration,Addition

Sample call:
http://service.civicpdx.org/housing-affordability/api/permits/?is_adu=true&new_class=New+Construction,Alteration,Addition
```
{
    "count": 2685,
    "next": "http://service.civicpdx.org/housing-affordability/api/permits/?is_adu=true&limit=10&new_class=New+Construction%2CAlteration%2CAddition&offset=10",
    "previous": null,
    "results": {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        -122.523985607596,
                        45.4941156891147
                    ]
                },
                "properties": {
                    "in_date": "1995-08-11T00:00:00Z",
                    "issue_date": "1995-08-29T00:00:00Z",
                    "status": "Final",
                    "year": 1995,
                    "new_class": "Alteration",
                    "new_type": "Accessory Dwelling Unit",
                    "neighborhood": "POWELLHURST-GILBERT",
                    "is_adu": "True",
                    "pdx_bnd": "YES",
                    "property_address": "3907 SE 136TH AVE",
                    "work_description": "Alteration",
                    "new_units": 1,
                    "valuation": "5200.00"
                }
            },
            ...
            {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        -122.67566405294,
                        45.5609260104243
                    ]
                },
                "properties": {
                    "in_date": "1995-06-09T00:00:00Z",
                    "issue_date": "1995-06-22T00:00:00Z",
                    "status": "Final",
                    "year": 1995,
                    "new_class": "Alteration",
                    "new_type": "Accessory Dwelling Unit",
                    "neighborhood": "HUMBOLDT",
                    "is_adu": "True",
                    "pdx_bnd": "YES",
                    "property_address": "826 N EMERSON ST",
                    "work_description": "Alteration",
                    "new_units": 1,
                    "valuation": "500.00"
                }
            }
        ]
    }
}
```

**The value we want to measure is `new_units`**, in order to get a visual on creation of units over time.

In the Story Collection Outline document it looks like we discussed doing these as horizontal lines to include all of them on a single chart, so feel free to go whichever route you think is best.

We suggest year filters from 1995 to 2017 for because data seems questionable/incomplete before and after that. To add a year filter just add `&year=XXXX` to the query. To do a year range filter use `&year_range_0=MIN&year_range_1=MAX`.

**Comment by adpeters** [comment]
@DingoEatingFuzz Now that I've added the API details I think this one should be ready for development. Let me know if we want to add or make an changes to the API.

**Comment by DingoEatingFuzz** [comment]
@adpeters, the api details you spelled out look great. This definitely looks ready for dev.

My one word of warning is that in order to have a smooth animation, all the data needs to be loaded upfront. If that ends up being too much to load at once, we may forego an animation in favor of some sort of year stepper/button bar.

**Comment by kmorrice** [comment]
Also, don't know if it was clear, but we are using 'year' to show values over time.

**Comment by Dianna** [comment]
@jaronheard https://github.com/orgs/hackoregon/projects/9

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
