### ISSUE TITLE
Neighborhoods over time for each age group

### ISSUE THREAD

**Issue by ylee22** [hackoregon/civic#193]
Civic Sandbox Foundation

Description: Change in neighborhood age demographics over time (5 groups, 18-25, 26-32, 33-39, 40-49, 50+)
Foundation / Slide: Foundation

Foundations:
What aggregation? (have your database/API team do this aggregation) Neighborhoods
What property should color the map? Percentage of total registered voters in the neighborhood in the specified age group
What additional property should be shown in the dashboard? Percentage of total registered voters in the neighborhood in the specified age group, then same percentage compared to city average
Is there a date/time component? What is the granularity of the date/time component? 2006-2016, 1 year intervals

**Comment by jaronheard** [comment]
Updated with information per our discussion @ylee22 @AraOshin

**Comment by hassanshamim** [comment]
this is on hold I suppose until we resolve hackoregon/neighborhoods-2018/issues/42

Will update when the endpoint is shaped as you need it.

**Comment by hassanshamim** [comment]
@jaronheard 

This is complete.  There are 2 endpoints you may want to use.  First has just the neighborhood name, year, and breakdown by age groups:
http://service.civicpdx.org/neighborhood-development/api/neighborhood_ages
You can filter by year with the `year` query param:
http://service.civicpdx.org/neighborhood-development/api/neighborhood_ages?year=2008&limit=200

There is an additional endpoint that returns the same data as above, but encoded in GeoJSON since we include the neighborhood polygons as well:

http://service.civicpdx.org/neighborhood-development/api/neighborhood_ages_geom

The geometries are generally pretty large data-wise.  So it may be advisable to use `neighborhood_ages_geom` on the first request and simply `neighborhood_ages` on subsequent requests.

Date ranges are 2006-2016

**Comment by jaronheard** [comment]
This is in the Civic Sandbox
