### ISSUE TITLE
Vulnerable Student Populations

### ISSUE THREAD

**Issue by NatalieRaketic** [hackoregon/civic#228]
- [ ] Needs a visualization that can be created from available data
- [ ] Needs available data in an API

Description / Wireframe

Students Eligible for Free and Reduced

Data Visualization / Design Concerns

The plot will allow you to navigate between school years (year selector)
This is NOT a Sandbox. This is a card in a map!
Card will use scatterplot layer, color by school type (5 categories), size by students eligible for free and reduced lunch, opacity by percentage eligible

![img_9350](https://user-images.githubusercontent.com/23616408/41136842-fe9b0d9a-6a8c-11e8-8995-1b4d5b831abd.jpg)

Context

Map of geocoded schools will be supplied to us
Data Details (APIs)

 dataset - ode_fr_lunch.csv
endpoints - TOTELGBLAMT,  and % of TOTELGBLAMT/Studenrcnt

About this data
This data was pulled from the ODE database
How did we calculate this
All values were calculated within the ODE data pull ( I think!) @jethard can confirm this.

See the source

**Comment by jaronheard** [comment]
This is a map inside of a card, not a sandbox card.

**Comment by jaronheard** [comment]
Currently, it looks like from the data, what we are closest to showing is the free and reduced lunch percentage over time by school. In order to do that, the school names will need to be cleaned, as they are not consistent over time.

We don't have data for location or any sort of aggregated statistic to compare to.

We also can't group by school category (e.g. K-5, 6-8, etc...), because we don't have category in the data.

I'm coming up short on how to show something meaningful with the data and time that we have. Chime in with ideas if you have them.

I feel like what we're closest to showing is a selector to choose a school, and then showing a line chart that shows that school in comparison to the national average, but some serious work needs to be done on this to make it viable.

**Comment by hassanshamim** [comment]
@jaronheard ahh this one fell through the cracks.  100% on me.

We do have better data for this now but still not geocoded.  Same data source as the `/api/student_demographics` endpoint, but I've combined the `free_reduced` and `direct_enrollment` columns into one which I've just called `free_reduced_pct`

I have included the school type in the response as well as the school size, % students who qualify for subsidized lunches as well as the raw count (school size * % qualified).

The endpoint is available here:  http://service.civicpdx.org/neighborhood-development/api/school_demographics/reduced_lunches

you can query by the `year`,`name`, or `type` similar to student demographic endpoints.
List of all school names available here: http://service.civicpdx.org/neighborhood-development/api/school_demographics/names

Very sorry this is coming in so late.  Let me know if there's anything else I can do to make consuming this API easier for frontend.

**Comment by jaronheard** [comment]
@hassanshamim @arailsya What do the the types delivered in the API stand for - what should the category labels say?

This is now ready. This should be a scatterplot, and can use identical infrastructure to StudentEnrollmentTrends.

**Comment by hassanshamim** [comment]
Ah.  Types are the type of school.  They can be any of the following: E, M, H, O, C

- Elementary School
- Middle School
- High School
- Charter School
- Other

**Comment by Dianna** [comment]
@jaronheard https://github.com/orgs/hackoregon/projects/9 ?

**Comment by Dianna** [comment]
Closing because cards requests must be made in https://github.com/orgs/hackoregon/projects/9 or the relevant data science repo to avoid permissions issues
