### ISSUE TITLE
update all link colors for site

### ISSUE THREAD

**Issue by karieleana** [hackoregon/civic#311]
- links are currently pink - which in small text is not accessible. update to civic blue: #1E62BD

<img width="1201" alt="screen shot 2018-06-20 at 9 41 23 am" src="https://user-images.githubusercontent.com/22756837/41672216-45b86b74-746e-11e8-8ba2-da41dffd669e.png">

<img width="1093" alt="screen shot 2018-06-20 at 9 42 46 am" src="https://user-images.githubusercontent.com/22756837/41672270-54f778b4-746e-11e8-85f4-046c6bdc9d17.png">

**Comment by etrainor** [comment]
Hi, 

I am interested in working on this issue. Is it still available?

Thanks!

**Comment by jaronheard** [comment]
@etrainor Hey, sorry for the slow response! This issue is still available if you're interested!

The main style for this lives in civic/packages/component-library/assets/global.styles.css -- but as a part of this issue, please see if there are any other links that use this color.

If you're feeling motivated, it might be great to knock out #509 at the same time

**Comment by jaronheard** [comment]
Closed via #559
