### ISSUE TITLE
WIP -> Housing: Homelessness Counts By Regions

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#59]
# Story Card Request

**Project: Housing**
**Card Title: Homelessness Counts by Region**

## API Details

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins
> So card developers can embed the links in the card.

## Wireframes

> Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> Once you have a wireframe, Include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

https://www.figma.com/proto/Sx4NhVdMgKdKKjPV6IEWIX7i/Housing-Card-Wireframes?scaling=contain&node-id=69%3A308

**Comment by kmorrice** [comment]
Excluding the Balance of States, Multnomah County ranks 17 out of 365. This is comparing across continuum of care entities.

**Comment by adpeters** [comment]
JSON Sample:
```
{
    "count": 117898,
    "next": "http://localhost:8000/api/homelessness/pit/?limit=10&offset=10",
    "previous": null,
    "results": [
        {
            "id": 1,
            "year": 2017,
            "datapoint": "AK-500",
            "datatype": "Total Homeless",
            "geography": "coc",
            "value": "1128.00"
        },
        {
            "id": 2,
            "year": 2017,
            "datapoint": "AK-500",
            "datatype": "Sheltered Homeless",
            "geography": "coc",
            "value": "973.00"
        },
        {
            "id": 3,
            "year": 2017,
            "datapoint": "AK-500",
            "datatype": "Unsheltered Homeless",
            "geography": "coc",
            "value": "155.00"
        },
        etc...
    ]
}
```

**Comment by jaronheard** [comment]
Similarly to #55, could you update with the latest details? I'd like to get the front-end team working on this since your API is ready. Please tag me once updated.

Please make sure to include the following:

- [ ]  API details, including which attributes are used for the following:
- rank, including how to get both the ranking and the total
- name of location - it's not clear to me in the sample above how determine the name of the geography
- total of continuum of care entities, used for length of bars in the comparison bar graph.

**Comment by kmorrice** [comment]
We still need to reach consensus on what we want to include in the ranking (see note above). Others feel free to chime in on this. I think we should include all continuum of care entities, including balance of state. These continuum of cares are not statistically meaningful geographic regions, and it does not make sense to exclude some.

The ranking is based on the data in the value field, which is based on the total homeless population in 2017 for each continuum of care. A rank of 1 is most homeless individuals, and a rank of 399 is the least homeless individuals. Portland-Gresham-Multnomah County is ranked 20 out of 399. Hillsboro/Beaverton/Washington County CoC is ranked 202. Clackamas County is ranked 216. The total is the number of continuum of cares for each respective year. Since we focused on 2017, the 399 number is the number of continuum of cares for that year. 

The name of the location is OR-505 (field is datapoint). OR-505 represents the continuum of care for Portland-Gresham-Multnomah County. OR-506 is Hillsboro/Beaverton/Washington County CoC. OR-507 is Clackamas County CoC. Hillsboro/Beaverton/Washington County CoC is ranked 202. 

For the total of continuum of care entities bar graph, I'm not sure exactly how we want that to be featured. It seems like it would be overload to include all 399 entities, but that would provide the most context. I'll let others chime in here.

**Comment by adpeters** [comment]
@jaronheard I've updated the API sample above. I've also added the CoC name to the datapoint. What do you mean by the "total fo continuum of care entities"? The count of entities or sum of their homeless values?

**Comment by jaronheard** [comment]
@adpeters reading back over this, I was confused as to what was being was ranked here. I guess the total that informs the length of the graph is "value", which represents the number of homeless people in a continuum of care entity. 

I think I now understand what is being asked for with this graph.

**Comment by adpeters** [comment]
@jaronheard Great, I've added `rank` and `total` fields to the json results.

**Comment by jaronheard** [comment]
Consolidated into issue #152

**Comment by jaronheard** [comment]
@kmorrice is this a count of homeless people, or is there also a count of homeless beds?

**Comment by kmorrice** [comment]
We're doing a count of homeless people. We were also thinking of doing a count of homeless beds, but I'm not sure what the status of that is. I think we'll talk about this a bit more tomorrow. I'm still unclear about this card, since I don't think we should do the rankings. I think looking at time series relevant to Portland would be good graphics to feature (homeless people over time, beds over time, etc.).

**Comment by jaronheard** [comment]
My understanding is that this isn't in the final story collection, so closing this issue.
