### ISSUE TITLE
2017 package is broken

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#793]
### Description

The 2017 package is not up to date with the latest changes to the master branch. Any child route with a map is broken and style changes have led to a broken UI where the pages can load.

### Steps to reproduce

Run the 2017 package or view the deployed version

### Expected result

The website should load and show the things

### Actual result

The website did not load and show the things

### Environment

Deployed and the master branch in development

**Comment by jaronheard** [comment]
@DingoEatingFuzz -- I propose the following temporary solution for the 2017 container, given that it's currently broken in a number of ways, and it was passing tests -- though it was intermittently failing.

It may not be a big lift to fix, but I think it is a big lift to ensure that it doesn't break again during all the changes that we'll be making between now and demo day.

If possible, I'd like roll back deployment of the 2017 container to last known working version, and stop CIVIC from deploying new versions, then after demo day make it work and write (end-to-end?) tests so that this doesn't happen again.

**Comment by DingoEatingFuzz** [comment]
Yep, makes sense.

So the steps will be...

1. PR to remove/disable the 2017 build in Travis
2. Manually redeploy the CIVIC 2017 site with last known working image (a date or travis build link would help here)

**Comment by jaronheard** [comment]
@DingoEatingFuzz I think this build should work? 

https://travis-ci.org/hackoregon/civic/builds/558092987?utm_source=github_status&utm_medium=notification

**Comment by jaronheard** [comment]
@DingoEatingFuzz Also #805 if you want to give a quick review.

**Comment by DingoEatingFuzz** [comment]
Fixed in prod.

**Procedure:**

1. Check if ECR has historical builds dating back that far (they prune after awhile to save on the storage bill)
2. ECR did not (makes sense, we have a lot of activity on this repo)
3. Make a local checkout at commit https://github.com/hackoregon/civic/commit/5f8b7ab19089b9d0cfb2bcf326b5daa373712d6a
4. Verify 2017 runs locally
5. Modify the deploy config to deploy when branch = `revert-2017` rather than `master`
6. Push branch
